### ISSUE TITLE
Something wrong while scrolling 

### ISSUE THREAD

**Issue by mustafa-707** [RafaelBarbosatec/tutorial_coach_mark#199]
i got this exception when i start scrolling between tags 

```

flutter: FormatException: It was not possible to obtain target position (temp_diff2).
flutter: #0      getTargetCurrent (package:tutorial_coach_mark/src/util.dart:42:7)
flutter: #1      AnimatedFocusLightState._runFocus (package:tutorial_coach_mark/src/widgets/animated_focus_light.dart:151:24)
flutter: #2      AnimatedPulseFocusLightState._runFocus (package:tutorial_coach_mark/src/widgets/animated_focus_light.dart:447:11)
flutter: #3      AnimatedFocusLightState._goToFocus (package:tutorial_coach_mark/src/widgets/animated_focus_light.dart:191:7)
flutter: #4      AnimatedPulseFocusLightState._listener (package:tutorial_coach_mark/src/widgets/animated_focus_light.dart:479:7)
flutter: #5      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
flutter: #6      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:897:7)
flutter: #7      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:913:5)
flutter: #8      Ticker._tick (package:flutter/src/scheduler/ticker.dart:261:12)
flutter: #9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
flutter: #10     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
flutter: #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
flutter: #12     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
flutter: #13     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
flutter: #17     _invoke1 (dart:ui/hooks.dart:330:10)
flutter: #18     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:397:5)
flutter: #19     _beginFrame (dart:ui/hooks.dart:272:31)
flutter: (elided 3 frames from dart:async)


```

version :  `1.2.12`
flutter : 3.24.5

**Comment by RafaelBarbosatec** [comment]
Fixed in #236 and released in **v1.3.4** 🚀 Thanks for the detailed report!
