### ISSUE TITLE
Null check operator used on a null value. Error thrown null

### ISSUE THREAD

**Issue by raunak-moonraft** [RafaelBarbosatec/tutorial_coach_mark#82]
@RafaelBarbosatec
This same issue is happening with me as well. We are using tutorial_coach_mark: ^1.0.3 (the latest version at present). Here is the crashlytics issue: -

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
at TutorialCoachMark.show.(tutorial_coach_mark.dart:80)
at _CustomZone.bindCallback.(dart:async)
at TickerFuture.whenCompleteOrCancel.thunk(ticker.dart:407)

Device OS Android 11

**Comment by RafaelBarbosatec** [comment]
Hi @raunak-moonraft !
Thanks for report this issue!
Try use 1.1.1 version.

**Comment by rohan20** [comment]
Running into the same issue. v1.2.4

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building TutorialCoachMarkWidget-[LabeledGlobalKey<TutorialCoachMarkWidgetState>#02fec](dirty, state: TutorialCoachMarkWidgetState#e37a7):
Null check operator used on a null value

The relevant error-causing widget was: 
  Navigator-[LabeledGlobalKey<NavigatorState>#df031] Navigator:file:///Users/redacted/Dev/redacted-project-name/lib/core/navigation/navigation_widget.dart:82:20
When the exception was thrown, this was the stack: 
#0      TutorialCoachMarkWidgetState._buildContents (package:tutorial_coach_mark/src/widgets/tutorial_coach_mark_widget.dart:150:39)
#1      TutorialCoachMarkWidgetState.build (package:tutorial_coach_mark/src/widgets/tutorial_coach_mark_widget.dart:105:20)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
```

**Comment by rohan20** [comment]
My bad. The issue was that I was initialising `targets` inside the `build` method instead of doing it just once in the `initState` method as the `README` rightly points out.

**Comment by ivanhercaz** [comment]
@RafaelBarbosatec, I had this problem following [the available example](https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/master/example/lib/main.dart) and I solved it following @rohan20 suggestion. May it be necessary to update the example?

**Comment by RafaelBarbosatec** [comment]
HI @ivanhercaz !
Yes, you need run the tutorial after you tree widgets already rendered.

**Comment by RafaelBarbosatec** [comment]
This crash (null check during the target position lookup) was addressed in v1.3.4: when a target's `GlobalKey` isn't attached to the widget tree, the package now handles it internally (`NotFoundTargetException`) instead of throwing a raw null-check error, and the tutorial finishes/skips cleanly. Update to `tutorial_coach_mark: ^1.3.4` and reopen if you still see it. Closing as resolved.
